### ISSUE TITLE
How to add description to try area?

### ISSUE THREAD

**Issue by strongdevx** [njleonzhang/docsify-demo-box-vue#1]
like elementui:

![image](https://user-images.githubusercontent.com/29698176/30676786-784e72ac-9eba-11e7-8c1d-823e5f7b5240.png)

**Comment by strongdevx** [comment]
I found,use desc tag:
<desc>
Hello world
</desc>

**Comment by njleonzhang** [comment]
@strongdevx I haven't mentioned explicitly this in Doc, will add in future.

**Comment by njleonzhang** [comment]
updated
