### ISSUE TITLE
How to import vue component?

### ISSUE THREAD

**Issue by strongdevx** [njleonzhang/docsify-demo-box-vue#2]
I have vue component :leafleft-map.vue
How to import vue component to md　file?

![af8699e8-d3d4-4f83-924e-6fb5c65b3220](https://user-images.githubusercontent.com/29698176/30798943-d175be66-a20d-11e7-817d-481d74a6f0f3.png)

**Comment by njleonzhang** [comment]
1. you need build your lib `leafLetMap` as `umd` lib.
2. loading in docsify index.html 
```
<script src="/path/of/your/lib/leafLetMap.js"></script>

Vue.use(YourLib)
```
This make the preview in `docsify` work

3. To make the sample work in jsfiddle, there are 2 methods:

    * leverage parameter `jsResources` and `bootCode` of `DemoBoxVue.create` for a global config.  **Adopt this method, if most of your demo sample in the doc all use this component.** samle: [index.html](https://github.com/njleonzhang/vue-data-tables/blob/master/docs/index.html), [quickstart](https://github.com/njleonzhang/vue-data-tables/blob/master/docs/quickstart.md)
    *  leverage comment `jsResource` to inject for special sample.(https://github.com/njleonzhang/vue-data-tables/blob/master/docs/event.md#filtered-data). **Adopt this method, if some your demo samples in the doc use this component.** sample: [event]

**Comment by strongdevx** [comment]
Thank you very much.The problem has been solved.

**Comment by denisdeng** [comment]
在docify中使用该插件，运行时报错，提示Babel is not defined。

配置如下：

` <script src="//unpkg.com/vue/dist/vue.js"></script>
  <script src="https://unpkg.com/docsify-demo-box-vue/dist/docsify-demo-box-vue.min.js"></script>
  <script>
var jsResources = '<scr' + 'ipt src="//unpkg.com/vue/dist/vue.js"></scr' + 'ipt>';
var cssResources = '@import url("//cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css");';
var bootCode = 'var globalVariable = "leon"';
var globalVariable = "leon" ;
window.$docsify = {
    name: '',
    repo: 'https://github.com/njleonzhang/docsify-demo-box-vue',
    plugins: [
        DemoBoxVue.create(jsResources, cssResources, bootCode)
    ],
    el: '#main',
    executeScript: true
}
  </script>
  <script src="//unpkg.com/docsify/lib/docsify.min.js"></script>`
